# import python packages

In [1]:
import pandas as pd
import glob, os
from pyswmm import Simulation, Links
# import multiprocessing as mp
# import matplotlib.pyplot as plt
# import fastparquet as fp

# delete files to avoid errors

In [3]:
# for f in glob.glob('../Output_SWMM_directory/*.parquet'):
#     os.remove(f)

# for f in glob.glob('../Output_SWMM_directory/*.out'):
#     os.remove(f)

# for f in glob.glob('../Output_SWMM_directory/*.rpt'):
#     os.remove(f)

# get hydrographs from link

In [2]:
Link_ID = '116'
Link_ID

'116'

# read SWMM filenames

In [2]:
swmm_files = []

for file in os.listdir('../Output_SWMM_directory/'):
    if file.endswith('.inp'):
        swmm_files.append(file)

swmm_files = pd.DataFrame(swmm_files, columns=['swmm_filename'])
swmm_files.sort_values(by='swmm_filename', inplace=True, ignore_index=True)
swmm_files

                                          swmm_filename
0       frequent______freq_0_2_EY___________010__01.inp
1       frequent______freq_0_2_EY___________010__01.out
2     frequent______freq_0_2_EY___________010__01.pa...
3       frequent______freq_0_2_EY___________010__01.rpt
4       frequent______freq_0_2_EY___________010__02.inp
...                                                 ...
1105    rare__________freq_2_percentage_____120__06.inp
1106    rare__________freq_2_percentage_____120__07.inp
1107    rare__________freq_2_percentage_____120__08.inp
1108    rare__________freq_2_percentage_____120__09.inp
1109    rare__________freq_2_percentage_____120__10.inp

[1110 rows x 1 columns]

# simulate SWMM files, export SWMM results

In [ ]:
hydrograph_list = []

for index_1 in swmm_files.index:
    a1 = swmm_files.swmm_filename[index_1]
    with Simulation(r'../Output_SWMM_directory/' + a1) as sim:
        Link_swmm = Links(sim)[Link_ID]
        temp_list = []
        for index_2, step in enumerate(sim):
            a2 = pd.DataFrame({'timestamp':[sim.current_time], 'flow':[Link_swmm.flow]})
            temp_list.append(a2)
        temp_list = pd.concat(temp_list, ignore_index=True)
        temp_list.to_parquet('../Output_SWMM_directory/' + a1[:-4] + '.parquet')
#         a3 = pd.DataFrame({'frequency':[a1[:-4][:14].split('__')[0]], 
#                            'freq_AEP':[a1[:-4][14:-7].split('__')[0]], 
#                            'duration':[int(a1[:-4][-7:-4])], 
#                            'pattern':[int(a1[:-4][-2:])], 
#                            'hydrograph':[temp_list]})
#         hydrograph_list.append(a3)

# hydrograph_list = pd.concat(hydrograph_list, ignore_index=True)
# hydrograph_list

In [16]:
# hydrograph_list = []

# for index_1 in swmm_files.index:
#     a1 = swmm_files.swmm_filename[index_1]
#     with Simulation(r'../Output_SWMM_directory/' + a1) as sim:
#         Link116 = Links(sim)['116']
#         temp_list = []
#         for index_2, step in enumerate(sim):
#             a2 = pd.DataFrame({'timestamp':[sim.current_time], 'flow':[Link116.flow]})
#             temp_list.append(a2)
#         temp_list = pd.concat(temp_list, ignore_index=True)
#         temp_list.to_parquet('../Output_SWMM_directory/' + a1[:-4] + '.parquet')
#         a3 = pd.DataFrame({'frequency':[a1[:-4][:14].split('__')[0]], 
#                            'freq_AEP':[a1[:-4][14:-7].split('__')[0]], 
#                            'duration':[int(a1[:-4][-7:-4])], 
#                            'pattern':[int(a1[:-4][-2:])], 
#                            'hydrograph':[temp_list]})
#         hydrograph_list.append(a3)

# hydrograph_list = pd.concat(hydrograph_list, ignore_index=True)
# hydrograph_list

,frequency,freq_AEP,duration,pattern,hydrograph
0,frequent,freq_0_2_EY,10,1,timestamp flow 0 2023-01...
1,frequent,freq_0_2_EY,10,2,timestamp flow 0 2023-01...
2,frequent,freq_0_2_EY,10,3,timestamp flow 0 2023-01...
3,frequent,freq_0_2_EY,10,4,timestamp flow 0 2023-01...
4,frequent,freq_0_2_EY,10,5,timestamp flow 0 2023-01...
...,...,...,...,...,...
805,rare,freq_2_percentage,120,6,timestamp flow 0 2023-01-...
806,rare,freq_2_percentage,120,7,timestamp flow 0 2023-01-...
807,rare,freq_2_percentage,120,8,timestamp flow 0 2023-01...
808,rare,freq_2_percentage,120,9,timestamp flow 0 2023-01-...
809,rare,freq_2_percentage,120,10,timestamp flow 0 2023-01-...

# get peak flow

In [17]:
# max_flow_list = []

# for index_3 in hydrograph_list.index:
#     b1 = hydrograph_list.hydrograph[index_3].flow.max()
#     max_flow_list.append(b1)

# max_flow_list = pd.DataFrame({'max_flow':max_flow_list})
# max_flow_list = pd.concat([hydrograph_list.iloc[:,:4], max_flow_list], axis=1)
# max_flow_list

    frequency           freq_AEP  duration  pattern   max_flow
0    frequent        freq_0_2_EY        10        1  14.064574
1    frequent        freq_0_2_EY        10        2  14.360415
2    frequent        freq_0_2_EY        10        3  13.859452
3    frequent        freq_0_2_EY        10        4  14.387873
4    frequent        freq_0_2_EY        10        5  14.211152
..        ...                ...       ...      ...        ...
805      rare  freq_2_percentage       120        6  15.925628
806      rare  freq_2_percentage       120        7   9.787742
807      rare  freq_2_percentage       120        8  15.020906
808      rare  freq_2_percentage       120        9  12.388422
809      rare  freq_2_percentage       120       10  14.134178

[810 rows x 5 columns]

In [20]:
# max_flow_list.groupby(by=max_flow_list.columns[1:3].to_list()).agg({'max_flow':['describe']})

                              max_flow                                  \
                              describe
                                 count       mean       std        min
freq_AEP             duration
freq_0_2_EY          10           10.0  14.409101  0.319253  13.859452
                     15           10.0  15.853758  0.482017  14.875977
                     20           10.0  15.792678  0.911690  14.507990
                     25           10.0  15.151653  1.031341  13.425577
                     30           10.0  14.986001  1.130143  12.908811
...                                ...        ...       ...        ...
freq_63_2_percentage 30           10.0  10.418170  1.178691   8.866056
                     45           10.0  10.706408  1.074772   9.373371
                     60           10.0   8.836923  1.877785   6.319579
                     90           10.0   7.401352  1.816300   5.133656
                     120          10.0   7.509702  2.088744   5.334485



                                     25%        50%        75%        max
freq_AEP             duration
freq_0_2_EY          10        14.248467  14.414546  14.522274  14.941526
                     15        15.868283  15.980652  16.076996  16.437045
                     20        15.052340  15.923456  16.414486  17.294208
                     25        14.643342  15.439248  16.027961  16.137153
                     30        14.414444  14.785836  15.926431  16.633668
...                                  ...        ...        ...        ...
freq_63_2_percentage 30         9.449410  10.190548  11.521269  12.165036
                     45         9.724737  10.724511  11.499954  12.297835
                     60         7.754791   8.384499  10.723472  11.370301
                     90         5.945402   7.316026   8.660668  10.419594
                     120        5.736988   7.170353   8.645799  11.429932

[81 rows x 8 columns]

In [19]:
# plt.boxplot()